### ISSUE TITLE
Feature restore wish: Simply clear content and place cursor

### ISSUE THREAD

**Issue by gh-ix** [fnxweb/neo-diggler#11]
Hello,

usually I work under X11, so selecting a text means overwriting current selection buffer.
Therefore I looked for a plugin - I guess when Firefox version read 3.x (yes, I guess around 10 years ago)...
Today there's waterfox, which would allow me to use the famous XPI Neo Diggler plugin, but I'd love to be able to use firefox Quantum and above too!!!
I'd donate 50 bucks for re-implementing the old icon-click behaviour!  First, I was excited that there's a webx plugin port, but the behaviour was a big surprise, which renders it useless for my limited needs unfortunately. (Btw., for consistency reasons I also use this plug on Windows together with 
pref("browser.urlbar.clickSelectsAll", false);

Thanks,
-harry

**Comment by fnxweb** [comment]
I use Linux myself.

Sorry, but I'm not entirely sure what you're after! Do you mean the left-click clear-the-URL bar feature?  If so, Firefox doesn't (currently) allow extensions to access the URL bar any more for security reasons.

That's why I added my own pop-up to simulate that (yes, to be able to middle-click paste the primary selection).

Is that not working for you?

**Comment by gh-ix** [comment]
Hello, thanks for your attention!
You exactly described the problem I have with the web extension version.
There was so many things to fix, but mozilla needs to re-write menus and de-enterprise FF on a bi-montly basis... Can't emphisize how much I cannot understand...
Unfortunately, the web extension version is no option - Firefox is not an option.
Will bundle the XPCOM version with waterfox.
Thanks,
-harry
